name: realm_cars
description: A flutter demo application using realm database

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  auto_route: ^7.1.0
  cupertino_icons: ^1.0.5
  flutter:
    sdk: flutter
  realm: ^1.0.3

dev_dependencies:
  auto_route_generator: ^7.0.0
  build_runner: ^2.3.3
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true